mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('', include('polls.urls', namespace='loginpage')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),  

]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.user_login, name='loginpage'),
    path('logout/', views.user_logout, name='logout'),
    path('<int:pk>/', views.valid_vote, name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    
]

mysite/polls/models.py
import datetime
from datetime import date, timedelta

from django import forms
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published' ,default=timezone.now)
    end_date = models.DateTimeField('ending date', default=timezone.now() + datetime.timedelta(days=10))
    
    def __str__(self):
        return self.question_text
        
    def was_published_recently(self):
        now = timezone.now()
        return now >= self.pub_date >= now - datetime.timedelta(days=1)

    def is_published(self):
        return timezone.now() >= self.pub_date

    def can_vote(self):
        return self.end_date > timezone.now() >= self.pub_date

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Vote(models.Model):
    """Create a model to track user vote."""

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, blank=True, 
                  on_delete=models.CASCADE, default=0)

mysite/polls/views.py
from django.utils import timezone
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render , redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import Choice, Question
from django.views.generic import TemplateView





class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')



class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def valid_vote(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if not question.can_vote():
        messages.error(request, f'You are not allowed to vote in the "{question.question_text}" poll!')
        return redirect('polls:index')
    return render(request, 'polls/detail.html', {'question': question})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                if request.user.is_superuser:
                    return redirect("admin:index")
                else:
                   return redirect("polls:index")
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Failed to login.")
            return HttpResponse("Invalid login details given")
    else:
        return render(request, "polls/loginpage.html", {})


def user_logout(request):
    logout(request)
    return render(request, "polls/loginpage.html")

mysite/polls/templates/polls/base.html
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'css/loginpage.css' %}">
</head>
</html>
<body>
    {% block content %}
    {% endblock content %}
</body>

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>
<a href="{% url 'polls:index' %}"> Back to List of Polls</a>

mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<h1 class="polls">Wellcome to KU Polls >>{% if user.is_authenticated %} <i>{{ user.username }} </i><a
    href="{% url 'logout' %}" class="button";> Click to Logout</a>
<div>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        <li>Publication Date: {{ question.pub_date }}</li>
        
        {% if question.can_vote %}<a href="{% url 'polls:detail' question.id %}">Vote</a>
        {% endif %}
            <a href="{% url 'polls:results' question.id %}">See result</a>
            
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% else %}<a
    href="{% url 'login' %}" class="button">Click to Login</a>{% endif %}</h1>

mysite/polls/templates/polls/loginpage.html
{% extends 'polls/base.html' %}
{% load static %}
<body>
    {% block content %}
  <div class="login">
    <form method="post" action="{% url 'polls:loginpage' %}" class="container">
      <h1>Login</h1>
      {% csrf_token %}
      <label for="User"><b>Username</b></label>
      <input type="text" name="username" placeholder="Enter Username" name="username" required>
      <label for="psw"><b>Password</b></label>
      <input type="password" name="password" placeholder="Enter Password" name="psw" required>
      <div class= "log-btn">
        <button>Login</button>
      </div>
    </form>
  </div>
  {% endblock content%}
</body>
</head>

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<div>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a> <br />
<a href="{% url 'polls:index' %}"> Back to List of Polls</a></div>